GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/62f16469f13b138a4dbf138

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Vishnu Kumar",
    "subscriberToChannel": "yoka yoka"
}
